### PR TITLE
Reorganize C v2

### PR DESCRIPTION
**Pull request by kwohlfahrt**
This should be the same as the previous one, but on top of v0.4

### CODE REVIEW

**Comment by grlee77** [comment]
looks good.  sorry it became a pain to rebase.  we should be able to merge ASAP after the release

This is a good example of how `add_subpackage` works, so I learned something new as well!

**Comment by grlee77** [comment]
It looks like the docstring changes to `_pywt.pyx` in #150 caused this to need another rebase.  Hopefully it should be simpler this time around.

**Comment by kwohlfahrt** [comment]
Should be good to go. Git is really bad at dealing with moving blocks of code it seems.

**Comment by grlee77** [comment]
If there is no further feedback on this one, let's merge it.  I plan to do so tomorrow if no one gets to it beforehand.

**Comment by rgommers** [comment]
> If there is no further feedback on this one, let's merge it. I plan to do so tomorrow if no one gets to it beforehand.

+1 from me

**Pull request merged**
