### PR TITLE
add common 1d synthetic signals

### PR DESCRIPTION
**Pull request by grlee77**
This PR adds a new function: `pywt.data.demo_signal`.  It implements many standard 1D test signals as used in the literature and in Stéphane Mallat's book "A Wavelet Tour of Signal Processing".

This function is an adapation of the function `MakeSignal` from the free [Wavelab](https://statweb.stanford.edu/~wavelab/) toolbox. I wrote to and received permission from Dr. Donoho to reproduce these signals within PyWavelets under its MIT license. 

The implemented signals are as follows (figures below were generated by the new demo added in this PR):
signals1
signals2
signals3
signals4

### CODE REVIEW

**Comment by rgommers** [comment]
Nice! +1 for adding these

**Comment by rgommers** [comment]
TravisCI is unhappy: one PEP8 error, some non-ascii symbol issues, plus an apparently unrelated random failure: `FAIL: test_concurrent.test_concurrent_cwt`

**Comment by grlee77** [comment]
>> plus an apparently unrelated random failure: FAIL: test_concurrent.test_concurrent_cwt

I have occasionally seen that on Travis in the past and it tends to pass if I restart the CI.  I added a commit where a small tolerance is used in place of exact equality.

**Comment by grlee77** [comment]
There was also a failure on 2.7 due to the special character in Stéphane.  adding `# -*- coding:utf-8 -*-` at the top of the file seems to have resolved it.

**Comment by rgommers** [comment]
All green, change to flaky test looks useful. In it goes. Thanks @grlee77

**Pull request merged**
