### PR TITLE
dwt_max_level: avoid taking uint_log2 of values<1

### PR DESCRIPTION
**Pull request by grlee77**
Fixes a bug in `dwt_max_level` when the input is shorter than the wavelet coefficient vector.

example of the bug on current master:
```python
In[19]: dwt_max_level(16, 24)
Out[19]: 16
```
after the fix, 0 is returned as expected.

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
Good catch, +1.

This is the only place `uint_log2` is used, but if it might be worth moving the check into `uint_log2` in case that changes (note `__builtin_clzl` is undefined for `x == 0`, but `_BitScanReverse` will return `0`).

**Comment by kwohlfahrt** [comment]
OK, I'm really nit-picking now, but the original change to `dwt_max_level` isn't necessary anymore, since `uint_log2` now has defined behaviour. Sorry!

**Comment by grlee77** [comment]
okay.  I left only the  `if(filter_len < 2)` check in place to avoid a potential divide by zero if `filter_len` is 1.

**Comment by kwohlfahrt** [comment]
That looks right to me, but not to AppVeyor. `_BitScanReverse64` might be worth a try? I'm not sure though, this is interesting. AppVeyor only says `AssertionError`, so if you have a windows toolchain to hand you might be better placed to debug.

**Comment by kwohlfahrt** [comment]
Hmm, that's not it. I'm sure there is a computer with MSVC on it around here somewhere, I'll see if I can track it down. This has me intrigued now.

**Comment by kwohlfahrt** [comment]
I misread the documentation of `_BitScanReverse` when implementing this. The **return value** is 0 if no set bits are found, not the output value loaded into the `Index` parameter. In this case, I think 795526e is the correct approach, though the comment accompanying `uint_log2` should note that the result is undefined for 0 on all platforms. This also mimics Python's behaviour (though that raises an exception of course).

There is a second problem I've come across, namely that on 64-bit platforms we should be using `_BitScanReverse64`, while on 32-bit platforms we should be using `_BitScanReverse`. The build warning about mismatching types is not flagged in AppVeyor, so I only came across it when debugging this on windows. I'll see if I can find anything appropriate.

Sorry this has dragged on for so long.

**Comment by grlee77** [comment]
should I remove the 9f9bb36 "merge" commit from here?

**Comment by kwohlfahrt** [comment]
I don't know - I think in past we've removed them, but a few seem to have snuck into the history anyway. Don't see any harm in doing it either way.

**Comment by rgommers** [comment]
Agreed, doesn't do harm either way. And in this case it's a small merge commit that reflects real development history, so much better than "merge master into development branch". The latter we do like to avoid.

**Pull request merged**
