### PR TITLE
BLD: add pyproject.toml file (PEP 518 support).

### PR DESCRIPTION
**Pull request by rgommers**
WIP because the debate is not completely finalized (https://github.com/pypa/pip/issues/4582). But wanted to get this in to not forget before the next release.

EDIT: not WIP anymore as commented on in a comment below. 

Closes gh-335

### CODE REVIEW

**Comment by rgommers** [comment]
Okay not WIP anymore, debate seems about settled. Rationale for the choice for Python 3.7 is at https://github.com/pypa/pip/issues/4582#issuecomment-315037686

**Comment by grlee77** [comment]
I have no prior experience with PEP 518.  Is Cython not here because the generated .c files are already included in the source distribution on PyPI?  If someone checks out the github source, though, the .c files are not included and Cython would required as well.

**Comment by rgommers** [comment]
> Is Cython not here because the generated .c files are already included in the source distribution on PyPI? 

Correct (plus, see below)

> If someone checks out the github source, though, the .c files are not included and Cython would required as well.

I'm not a fan of treating Cython like a Python package. It's a compiler, and it's only coincidental that ``pip`` can install it. I prefer to treat Cython the same as you'd treat a C compiler - with build docs.

**Comment by grlee77** [comment]
I take it you would be against this suggestion over at https://github.com/pyFFTW/pyFFTW/issues/31 to remove the cython-generated .c file from source distributions then?.  I see that the Cython docs do suggest including the .c code as we have done in PyWavelets and PyFFTW:  http://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules.

**Comment by rgommers** [comment]
I think those comments on the pyFFTW issue are correct in principle but not in practice. This was also discussed a week or so ago on distutils-sig, and one of the points made there was that distributors should anyway not start from a PyPI tarball but from the git tag for the release. ``sdist``s will always contain generated files.

Maybe in a few years this'll change, but I think it's fundamentally about removing a build dependency and avoiding issues with different versions of Cython, at almost no cost (a couple of Mb larger downloads isn't a big deal).

**Comment by grlee77** [comment]
Sounds reasonable.  Thanks for the feedback.

**Comment by rgommers** [comment]
Updated for final format. @grlee77 any objections to merging this once TravisCI is happy?

**Comment by grlee77** [comment]
Looks good. Thanks

**Comment by grlee77** [comment]
Hi @rgommers , one other question related to the implications of this PR:

I see in [this comment](https://github.com/pypa/pip/issues/4582#issuecomment-312111015) a recommendation to update the `install_requires` in wheels to match the NumPy used at build time.  Is this necessary in practice?  How is scipy currently handling this?

It seems that the versions chosen here tend to be the oldest ones for which NumPy wheels exist for a given Python version, so I think if a user pip installs everything they would not encounter issues. 
 However, I suppose there may be some corner cases such as one where a user manually compiled an older NumPy but then tries to pip install PyWavelets.

(I am currently trying to sort this out for pyFFTW too in pyFFTW/pyFFTW#204)

**Comment by rgommers** [comment]
Yes, the correct version specifier should be `>=` of the version that is in pyproject.toml as `==` (because numpy ABI is backwards but not forwards compatible). This should be safe to add now with pip 10; the previous worries about poor `pip --upgrade` behavior have been resolved by a change in its defaults.

**Pull request merged**
