### PR TITLE
TST: fix misc. doctest failures (test_doc.py)

### PR DESCRIPTION
**Pull request by grlee77**
`test_doc.py` was apparently not being run on the CI services and had a number of failures.

### CODE REVIEW

**Comment by grlee77** [comment]
Thanks to @rafat for pointing out the issue in openjournals/joss-reviews#1237

It seems that `nosetests` was skipping `test_doc.py` entirely, so I modified the `.travis.yml` to run the tests in this file with a separate python call.

**Comment by grlee77** [comment]
If I don't hear any objections I'll go ahead and merge this one soon.

I'm not a fan of doctests in general, but since we have them currently, we should run them on CI to make sure they don't get out of date like this in the future.

**Comment by rgommers** [comment]
Thanks @grlee77. All green, so helpful for now.

> I'm not a fan of doctests in general, but since we have them currently, we should run them on CI to make sure they don't get out of date like this in the future.

Agreed. I actually like *examples* in doctest format, the problem is just that `doctest` itself is terrible. https://github.com/scipy/scipy/blob/master/tools/refguide_check.py fixes that. we can copy that at some point if needed (or wait till it gets turned in a standalone package).

**Comment by grlee77** [comment]
> https://github.com/scipy/scipy/blob/master/tools/refguide_check.py fixes that. we can copy that at some point if needed (or wait till it gets turned in a standalone package).

Actually we already have it in `util/refguide_check.py` and one of the Travis cases calls it, but perhaps it is not configured correctly? It currently only seems to check the examples in the `demos` folder, but doesn't actually seem to run any doctests.

**Comment by rgommers** [comment]
Ah good catch. It will need the `--doctests` flag.

**Comment by grlee77** [comment]
> Ah good catch. It will need the --doctests flag.

I tried that, but it doesn't seem to do anything. The full output is

```
Running checks for 0 modules:
Checking examples files at /home/lee8rx/my_git/pyir/pywt/doc/source/regression/*.rst:

dwt-idwt.rst .
gotchas.rst .
index.rst .
modes.rst .
multilevel.rst .
wavelet.rst .
wp.rst .
wp2d.rst .

OK: refguide and doctests checks passed!
```

For comparison, `python pywt/tests/test_doc.py` outputs
```
.........................................
----------------------------------------------------------------------
Ran 41 tests in 0.039s

OK
```


Finally there is the ability to run `make doctest` from within the `doc` folder. I don't think this is currently done on CI, but the summary produced by that is:
```
Doctest summary
===============
  379 tests
    0 failures in tests
    0 failures in setup code
    0 failures in cleanup code
```
I think it is more than the above mainly due to inclusion of additional regression tests from `doc/source/regression/`

**Pull request merged**
