### PR TITLE
DOC: Document MSVC versions

### PR DESCRIPTION
**Pull request by kwohlfahrt**
Document which MSVC is used for the official binary builds of python.

### CODE REVIEW

**Comment by grlee77** [comment]
LGTM

**Comment by rgommers** [comment]
See also http://mingwpy.github.io/issues.html#choice-of-msvc-runtime

**Comment by kwohlfahrt** [comment]
@grlee77 I don't think this war merged?

**Comment by grlee77** [comment]
whoops! sorry about that.

**Pull request merged**
