### PR TITLE
BLD: pin cython language level to '2'

### PR DESCRIPTION
**Pull request by tacaswell**
This is a simpler alternative to
https://github.com/PyWavelets/pywt/pull/435

### CODE REVIEW

**Comment by tacaswell** [comment]
Given that the next version of cython is going to change the default, it may be worth doing a bug-fix release with this change?

**Comment by tacaswell** [comment]
I have a script the builds master branch of the whole stack.  Without this patch pywt does not build against cython master.

**Comment by tacaswell** [comment]
To clarify, on cython master they now default to lanugage level "3str".

**Comment by rgommers** [comment]
Ah okay. We've already dropped 2.7 in master, so changing this to `language_level: 3` is the way to go I think. And closing gh-434. @grlee77 agree?

**Comment by grlee77** [comment]
I agree adding `language_level` as done here is cleaner, but I think the various import syntax changes in gh-435 will still be necessary in order for this to work with language level 3. I can update gh-435 to just remove the language_level statements from the separate files and put it in setup.py instead as done here.

**Comment by rgommers** [comment]
sounds good to me

**Comment by rgommers** [comment]
Allright, merged gh-434 which has the `language-level: 3` that came out of this PR. So closing this. Thanks @tacaswell

**Comment by tacaswell** [comment]
Great!

It may still be worth putting this change in a bug fix release.

**Comment by grlee77** [comment]
Yeah, that is a good idea.  I made a PR of this commit vs. the 1.0.x branch in #454.

**Pull request closed without merging**
