### PR TITLE
only run doctests on numpy 1.13

### PR DESCRIPTION
**Pull request by grlee77**
This is an alternative to #344 where I attempt to avoid running the doctests except in a single case on Travis which is currently set to use numpy 1.13.

Alternatively, we can update the docstrings to match 1.14 and use that version for the doctests.

### CODE REVIEW

**Comment by grlee77** [comment]
Travis seems happy with this, but Appveyor is still running the doctests for some reason.  Any idea why?  I though changing the `setup.cfg` would disable it because it just seems to call `nosetests`.

**Comment by rgommers** [comment]
Deleting `pywt/tests/test_doc.py` should fix things I think.

**Comment by grlee77** [comment]
> Deleting pywt/tests/test_doc.py should fix things I think

Thanks @rgommers.  somehow I had missed this comment at the time.  I didn't even realize we had a test_doc.py!  #344 is succeeding now too.  Can you merge either that PR or this one (once CI completes) and close the other?  I don't have a strong preference either way.  I just want to get CI working properly again for other pending PRs.

**Comment by grlee77** [comment]
doctests are still being run for some reason.  I am going to close this in favor as #344 which uses legacy printing on numpy 1.14 so that the doctests pass.

**Pull request closed without merging**
