### PR TITLE
Add Python 3.9 to CI and classifiers

### PR DESCRIPTION
**Pull request by grlee77**

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM, thanks @grlee77

**Comment by rgommers** [comment]
Let's drop Python 3.6 in a follow-up? Even NumPy is dropping it in the next release.

**Comment by grlee77** [comment]
> Let's drop Python 3.6 in a follow-up? Even NumPy is dropping it in the next release.

We did that previously in #559  :)

Do you mind if I add Python 3.9 wheels to the existing release or should we bump the version to do that? scikit-image is preparing a new release and PyWavelets is a dependency for it so I would like to get 5.9 wheels up

**Comment by rgommers** [comment]
> We did that previously in #559 :)

That was incomplete then, the [first TravisCI job on this PR](https://travis-ci.org/github/PyWavelets/pywt/jobs/742042777) uses 3.6, second one too.

> Do you mind if I add Python 3.9 wheels to the existing release

That should be fine, please go for it!

**Comment by grlee77** [comment]
> That was incomplete then, the first TravisCI job on this PR uses 3.6, second one too

I think those got unintentionally added later when adding ARM builds. It seems to be fixed by #579

**Pull request merged**
