### PR TITLE
Upgrade to Pillow>=3 api

### PR DESCRIPTION
**Pull request by asnt**
Fix for #191.

### CODE REVIEW

**Comment by grlee77** [comment]
LGTM.  just to clarify, the modified code also works for PILLOW 2.x?

**Comment by asnt** [comment]
I have only tested with Pillow 3.3. However, it seems tostring() has been deprecated since version 2.2: https://github.com/python-pillow/Pillow/blob/2.2.x/PIL/Image.py#L560

**Comment by grlee77** [comment]
Thanks @asnt

**Comment by rgommers** [comment]
@asnt we're listing names of contributors to every release in the release notes. For the next release those notes are in gh-206. We'd be happy to list your name instead of your Github handle if you tell us what it is.

**Pull request merged**
