### PR TITLE
Replace some .src expansion with macros

### PR DESCRIPTION
**Pull request by kwohlfahrt**
This replaces the simple instances of .src expansion (where the whole file is expanded to a `float` and `double` version) with macros. Essentially: `@type@_xyz` becomes `CAT(TYPE, _xyz)`, where `TYPE` must be defined where the template file is included. `CAT` is defined in templating.h

The main advantage is greatly improved compiler diagnostics (and debugging with GDB), because the compiler actually knows where the problematic lines came from.

My other work (fast dwtn, swt) is based on top of this, because it is much easier to work with the C parts.

### CODE REVIEW

**Comment by grlee77** [comment]
This all looks good to me.  I appreciate the work you have been putting into improving the usability of the C code.

**Comment by kwohlfahrt** [comment]
AppVeyor [passed](https://ci.appveyor.com/project/rgommers/pywt/build/1.0.46).

**Comment by rgommers** [comment]
Looks good to me too. The extra lines needed in ``setup.py`` are a small price to pay for the gains you get here.

**Comment by rgommers** [comment]
Looks good and other PRs depend on this, so let's just get it in. Thanks @kwohlfahrt

**Pull request merged**
