### PR TITLE
MAINT: ensure tests are included in wheels

### PR DESCRIPTION
**Pull request by rgommers**
Also test install via sdist and wheel on TravisCI. Closes gh-280.

### CODE REVIEW

**Comment by rgommers** [comment]
A test unrelated to this PR is failing:

    FAIL: test_deprecations.test_MODES_attributes_usage_deprecation
    ....
    AssertionError: No warning raised when calling dwt

**Comment by rgommers** [comment]
I can't reproduce the failure locally, but it's consistent on TravisCI it looks like. I'm tempted to just delete that test. We're removing that deprecated code anyway before the next release.

**Comment by grlee77** [comment]
the same error is also present in python 2.7 on Appveyor, but I do not see it locally when using 2.7.

I would be find with removing that test.

**Comment by grlee77** [comment]
Nice to see tests for wheel and sdist builds were added on Travis!

I see you have included the files via `package_data` rather than adding an `__init__.py` in the test folders.  I don't see a problem with doing it that way, but out of curiosity, do you recall the drawbacks of the `__init__.py` approach?

**Comment by rgommers** [comment]
Failing test removed, seems happy now.

**Comment by rgommers** [comment]
> do you recall the drawbacks of the ``__init__.py`` approach?

One is that ``tests`` will start to show up when tab-completing. There was something more subtle as well, but can't remember.

**Comment by grlee77** [comment]
Thanks @rgommers!

**Pull request merged**
