### PR TITLE
Fix corner case for small scales in CWT

### PR DESCRIPTION
**Pull request by grlee77**
When scales is much smaller than one, indexing-related errors as reported in #379 can occur.  

The length of a convolution is `len(data) + len(filter) - 1` and there is also a `numpy.diff` operation in the CWT which shortens the output of the convolution by 1.  The combination of these effects mean that the CWT coefficients are only longer than the input for filters of at least length 3.  Shorter scales that lead to sampled filters of shorter length are not handled correctly.  This PR handles the filter length 2 case properly and raises a more informative error for the length 1 case.

Note: Matlab does something slightly different in the length 1 corner case.  It does not raise an error, but returns values extremely close to zero (e.g. on the order of 1e-14).  I don't know exactly what the underlying difference is in their implementation, but don't think it is of much practical consequence. 

I have tried to clarify the docstring to provide at least minimal guidance on choosing values for `scales`.

The final commit here is unrelated and just removes some unnecessary repeat calls to `integrate_wavelet`

### CODE REVIEW

**Comment by grlee77** [comment]
One could argue that both of these corner cases should raise an error as each corresponds to the scaled wavelet having an overall length <= a couple of sampling periods of the data which is unlikely to be of practical use.

I think it was unclear from the documentation that "scales" is not supposed to be a frequency in Hz, but is instead a related in a more complicated manner frequency.  Most likely this issue is part of the reason Matlab decided to redesign their CWT routines for a couple years back.  The current release of Matlab still supports the older CWT API, but it is no longer the recommended choice.

**Comment by grlee77** [comment]
It would be great if @holgern or someone with more CWT expertise could verify that the proposed documentation changes here are correct (and/or provide feedback in #379).

**Comment by rgommers** [comment]
> Note: Matlab does something slightly different in the length 1 corner case. It does not raise an error, but returns values extremely close to zero (e.g. on the order of 1e-14). I don't know exactly what the underlying difference is in their implementation, but don't think it is of much practical consequence.

Agree that raising an error for length 1 is very reasonable.

**Comment by rgommers** [comment]
Okay, in it goes. Thanks @grlee77

**Pull request merged**
