### PR TITLE
TST: test Python 3.5 builds on Appveyor.

### PR DESCRIPTION
**Pull request by rgommers**
If this works, we can also upload 3.5 wheels to PyPi for v0.4.0

### CODE REVIEW

**Comment by grlee77** [comment]
It looks like Appveyor couldn't find an appropriate wheel for numpy, so it tried building from source and failed.

**Comment by grlee77** [comment]
I see a python 3.5 wheel for numpy 1.9.3 at:
http://28daf2247a33ed269873-7b1aad3fab3cc330e1fd9d109892382a.r6.cf2.rackcdn.com/
but Appveyor is trying to find one for numpy 1.8.1, which only has wheels for 2.7 and 3.4

**Comment by rgommers** [comment]
Hmm, 32-bit 3.5 build now works, but for the 64-bit build compiling Cython fails. Looks like we need Cython wheels for Python 3.5.

**Comment by rgommers** [comment]
There are now Cython 0.23.4 Windows wheels on PyPi (https://pypi.python.org/pypi/Cython/) so let's give those a try.

**Comment by rgommers** [comment]
OK Cython problem solved, now it fails to compile ``_pywt.c``. Probably due to the ``USE_SDK`` stuff in ``run_with_env.cmd``. Not fun to fix - I'm going to hunt for a solution in other ``appveyor.yml`` files.

**Comment by rgommers** [comment]
All green now!

**Comment by grlee77** [comment]
great!  I will upload these to pypi as well.

**Comment by grlee77** [comment]
Actually, these are labeled as 0.5.0dev, so probably shouldn't be uploaded as is.  Should we make a separate PR using these appveyor modifications merged onto the v0.4.0 tag or is there an easier way?

**Comment by rgommers** [comment]
I don't think there's an easier way. Merge this, then on top a new PR changing the version number to ``0.4.0`` I think. If there's no other code changes yet than that works fine (so better do this before merging the ``reorganize v2`` PR.

**Pull request merged**
