### PR TITLE
DOC: add Tidelift links to README.rst

### PR DESCRIPTION
**Pull request by grlee77**
Link to Tidelift security and landing pages from the readme.

### CODE REVIEW

**Comment by grlee77** [comment]
Yeah, I was not sure the best wording/location. I think it is required to put a link to the landing page somewhere, but it sounds like it could also be in the docs or on the PyPI page or something if there are objections to having it in the main readme.

**Comment by rgommers** [comment]
I think the main README is fine, otherwise there really is no point. And I would like Tidelift to grow their business, so our revenue streams (as in for PyWavelets, NumPy, SciPy, Pandas, and so on) grow with it.

The one thing I'm hesitant about is the "supported PyWavelets" phrase. That's a broad claim, which may suggest people can get bug fixes through Tidelift - which is not the case. On the other hand, if we all lots of disclaimers to that phrase, then again what's the point. So I'm fine to leave it as is for now. So far it hasn't given any problem for other packages.

**Comment by grlee77** [comment]
> The one thing I'm hesitant about is the "supported PyWavelets" phrase. That's a broad claim, which may suggest people can get bug fixes through Tidelift - which is not the case

The three example phrasings given in the Tidelift docs are:
```
- Professionally supported PyWavelets is now available 

- Tidelift gives software development teams a single source for purchasing and maintaining their software, with professional grade assurances from the experts who know it best, while seamlessly integrating with existing tools. 

- Get supported PyWavelets with the Tidelift Subscription 
```

Option 1 has the same issue you raised and two sounds like more of an advertisement to me so I went with three. We are not bound to use those exact examples, though. A more conservative phrasing (additions/changes in bold here for emphasis) might be:

As of 2019, PyWavelets development is supported **in part** by Tidelift. **Help support** PyWavelets with the Tidelift Subscription.

**Comment by rgommers** [comment]
> As of 2019, PyWavelets development is supported in part by Tidelift. Help support PyWavelets with the Tidelift Subscription.

I like that

**Comment by rgommers** [comment]
Okay, in it goes. Thanks @grlee77

**Pull request merged**
