### PR TITLE
Add Ability to Display a Progress Bar

### PR DESCRIPTION
**Pull request by TariqAHassan**
By default, no progress bar is displayed to conserve the previous default behavior.

### CODE REVIEW

**Comment by rgommers** [comment]
@TariqAHassan a progress bar in a function like ``cwt`` is highly unusual. Why do you think this is a good idea? And how slow is that ``for``-loop for you?

**Comment by TariqAHassan** [comment]
Yeah, I thought I may get that question. I am working with audio (long classical music pieces) on a fairly fast computer and the computations still take 4+ minutes. 

If you're primarily using `cwt` with short signals, I can see how a progress bar would seem odd. However, with medium sized audio clips it is pretty easy to find one's self with 15B+ element arrays (even using a low sample rate). If you combine that with the need to use a large number of scales, the calculation quickly becomes very expensive.

Lastly, I might add that the need to perform CWT on long arrays of complex signals is unlikely to be that uncommon, given the pervasiveness of audio data (particularly music).

Best,
Tariq

**Comment by kwohlfahrt** [comment]
As an alternative, perhaps monkey-patching it something like this (not sure, haven't really contributed much since the addition of CWT) could work:

```
def cwt(data, scales, *args, **kwargs):
  with tqdm(total=len(scales)) as pbar:
    tmp = pywt._cwt.integrate_wavelet
    def wrapper(*args, **kwargs):
      pbar.update(1)
      return tmp(*args, **kwargs)
    pywt._cwt.integrate_wavelet = wrapper
    pywt.cwt(data, scales, *args, **kwargs)
```

That way, people can add whatever callback function they like to keep track of `cwt` if it is too slow.

**Comment by rgommers** [comment]
Agree with @kwohlfahrt, it's easy to make a little wrapper function that adds a progress bar. This doesn't really belong in ``pywt``. So I suggest we close this PR.

**Comment by TariqAHassan** [comment]
@rgommers Fair enough. However, it would be nice if kwohlfahrt's code snippet could land somewhere so it's available to others, e.g, the docs.

**Comment by rgommers** [comment]
It seems to me that we should never encourage people to rely on private objects like ``pywt._cwt`` - it works now, but if we want to allow this kind of thing and put it in the docs, we should add a callback mechanism to ``cwt`` instead. Which seems overkill, so how about just passing in ``scales`` in smaller chunks? Something like (untested but should work):

    def cwt(data, scales, *args, **kwargs):
        with tqdm(total=len(scales)) as pbar:
            for scale in scales:
                # simplest version, can also break scales in chunks of size >1
                pbar.update(1)
                pywt.cwt(data, scale, *args, **kwargs)

**Pull request closed without merging**
