### PR TITLE
DOC: add v0.3.0 release notes

### PR DESCRIPTION
**Pull request by rgommers**
Also add some utility scripts (stolen from Scipy) to easily update the release notes.

### CODE REVIEW

**Comment by rgommers** [comment]
With this PR and the one for fixing version numbering I think we're about ready to tag the release.

**Comment by grlee77** [comment]
LGTM

**Comment by rgommers** [comment]
Pushed a couple more commits to address the move to the new org, version numbering in the docs, etc.

**Comment by rgommers** [comment]
@grlee77 if you want to check that the last commits look good, then I think we can merge this and tag v0.3.0

**Comment by rgommers** [comment]
@grlee77 if you want to check that the last commits look good, then I think we can merge this and tag v0.3.0

**Comment by grlee77** [comment]
not sure if it was intentional, but there is still one reference to http://www.pybytes.com/pywavelets/ in index.rst.  
Otherwise this looks good to me.

**Comment by rgommers** [comment]
Thanks, good catch. Forgotten to sync README.rst and index.rst. Those probably shouldn't be exact copies of each other (different purposes), but that's for another time. Fixed in amended last commit.

PEP 400 version fix is needed for Appveyor PR - ``pip`` refuses to install something called ``0.3.0.dev-`` now.

**Pull request merged**
