### PR TITLE
Test AppVeyor Status

### PR DESCRIPTION
**Pull request by kwohlfahrt**
I've opened an AppVeyor account in my name, just to play with getting statuses working. Sorry for the noise.

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
OK, it seems to work even with my webhook disabled. I think GitHub must have changed the permissions it required, and authorizing it to a new account probably enabled them.

In the "Third-party access" tab of the organization settings, "AppVeyor" is the original permission, and "AppVeyor CI" is the new one that I was prompted for.

**Comment by kwohlfahrt** [comment]
re-delivering old test requests also works, and updates their statuses on the respective PRs. Once these have completed I'll delete my AppVeyor project, since it is working currently with only the old webhook enabled.

**Comment by kwohlfahrt** [comment]
I've removed my AppVeyor project, and deleted the corresponding website. Everything should be back where it was before, apart from the additional setting in "Third-party access" of the "PyWavelets" organization. Resubmitted a couple of the old appveyor requests and statuses are showing up in the respective PRs. Looks fixed, if nothing breaks in the next few days we can close this without merging and close #94

**Comment by rgommers** [comment]
Fantastic! Thanks Kai.

**Comment by grlee77** [comment]
it seems all is well with AppVeyor now.   Thanks @kwohlfahrt

**Pull request closed without merging**
