### PR TITLE
Run doctests on TravisCI

### PR DESCRIPTION
**Pull request by grlee77**
This is an initial attempt to run doctests for `doc/source/regression/*.rst` via a modified copy of scipy's `refguide_check.py` on Travis as suggested in #210.

I am not currently running a reference guide check, but just `--doctests` .

@rgommers:
I could use some feedback on this.  A couple of specific things:
- Travis was failing until I switched to doing a `pip install -e .` in the last commit.  If I keep the install the same as for the nose testing cases, the doctests give a ton of errors related to `pywt` not being imported.  (I guess the way I have it now also tests that the pip development mode install is working)
- I only run the doctests for python 3.  Python 2.7 fails with errors related to the print function (there are calls to print using the `end` keyword in some tests)

### CODE REVIEW

**Comment by rgommers** [comment]
> I only run the doctests for python 3. 

That seems fine to me. This ensurer that there are no missing imports or broken code.

> Python 2.7 fails with errors related to the print function (there are calls to print using the end keyword in some tests)

Hmm, I think we should fix those. It's not hard to make all examples Python 2.7 compliant.

**Comment by rgommers** [comment]
Don't quite understand the import issue, seems odd. But well, ``doctest`` is quite odd. If it works this way, let's just leave it as is. Can't hurt to test a different way of installing either.

**Comment by grlee77** [comment]
Oddly enough, all tests pass on 2.7 if I go in the `/doc` folder and run `make doctest`.  I only see the handful of failures0 when I run them via `refguide_check.py`.  Somehow the `from __future__ import print_function` statements near the top of [wp2d.rst](https://github.com/PyWavelets/pywt/blob/e1c1c9104764c2fa1a1d600ffdf5685abcd12e2e/doc/source/regression/wp2d.rst) as well as `wp.rst` don't seem to take effect in the latter case.  Any idea why this could be?

**Comment by rgommers** [comment]
not sure. there's some special-casing of ``print_function`` (it's removed from ``__all__``) but it doesn't look wrong to me.

**Comment by grlee77** [comment]
Looks like the python 2.7 problem with `refguide_check.py` may be the same thing reported here.  
http://bugs.python.org/issue23043

That doesn't answer how the the sphinx `make doctest` is getting around that failure, but don't think it is worth spending much time looking into it.  I think testing on python 3 should be sufficient for the CI.  The doctests as written will work for users on 2.7 when run interactively (assuming the don't skip the `from __future__ import print_function` line).

**Comment by rgommers** [comment]
> don't think it is worth spending much time looking into it. I think testing on python 3 should be sufficient for the CI.

Agreed.

The PR title still says WIP, but it's good to merge now right?

**Comment by grlee77** [comment]
yes.  I think it is good to go

**Comment by rgommers** [comment]
Great, in it goes then. Thanks @grlee77

**Pull request merged**
