### PR TITLE
Improved coefficients for db and coif

### PR DESCRIPTION
**Pull request by holgern**
* add db coefficients up to db36
* add coif coefficients up to coif17
* increased accuracy for all db coefficents and coif coefficients
* coefficients for db and coif are calculated from the rec_lo_ coefficients
* epsilon for perfect_reconstruction_test increased again to epsilon = 5e-11

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
I'm on board with these changes, especially calculating the coefficients for db/coif on demand. I think this should be possible for the symlets as well?

The tests look OK, failure looks to be from a lack of MATLAB reference data for the new wavelets. I don't have MATLAB handy to generate more, I think this is a job for @aaren?

This probably should be rebased onto #161, or at least the part of it that modifies `wavelets.c[.src]` (503821d) since that has been unanimously approved so far. I'm happy to help with this.

**Comment by aaren** [comment]
@kwohlfahrt I've got matlab r2013a on me now. Should be able to generate the reference data.

**Comment by kwohlfahrt** [comment]
Great, it should probably go to @holgern so he can merge it into this. Open a PR against his branch?

**Comment by aaren** [comment]
Yep, will do. I can generate the data fine, except that matlab doesn't include coif > 5 (db is ok). I've checked on r2015b as well.

I could modify the test to exclude coif > 5 or I can add the computed values from this PR as reference data for coif > 5.

**Comment by kwohlfahrt** [comment]
@aaren probably useful to split out the matlab reference from the others. So disable that test for coif > 5, and create a separate data file and test using the new values as a reference for coif > 5.

**Comment by holgern** [comment]
What are the next steps? Can i help even further?

**Comment by kwohlfahrt** [comment]
The next step would be to add the missing MATLAB data for the compatibility tests, and some new reference data for the remaining wavelets.

Poking @aaren - can you open a PR against @holgern's repository to add this?

There's still some discussion on #161, so I've split out the part that will conflict with your changes into #169 since that was pretty much unanimously approved. I'll merge that tomorrow morning unless there are objections and then you'd need to rebase/merge that branch (in the meantime, it's kwohlfahrt@503821d . It quite significantly changes the structure of `wavelets.c.src` and `wavelets_coeffs.template.c`, so that'll be a bit of work I'm afraid. I'll help with that as mentioned before, but I might not have time to do so before early next week.

**Comment by aaren** [comment]
@kwohlfahrt @holgern I should get round to this tonight. Will make a PR against @holgern's branch.

**Comment by holgern** [comment]
I found out, that my institute has one academic matlab license for 2015b with wavelet-toolbox. I hope it I hope it is ok @aaren , that i am already created missing Matlab data.

**Comment by aaren** [comment]
Yeah, no problem. I guess you've already found it, but the data generation script is at `pywt/tests/data/generate_matlab_data.py`.

**Comment by holgern** [comment]
The matlab coeffients are different scaled by (sqrt(2)), 
E.g. matlab: 
>> dbwavf('db1')

ans =

   0.500000000000000   0.500000000000000
pywt:
w=pywt.Wavelet('db1')
w.rec_lo
[0.7071067811865476, 0.7071067811865476]

**Comment by holgern** [comment]
Sorry my fault, wfilter gives the same scaling:
[Lo_D,Hi_D] = wfilters('db1','d')

Lo_D =

   0.707106781186548   0.707106781186548


Hi_D =

  -0.707106781186548   0.707106781186548

**Comment by holgern** [comment]
The matlab test is failing as the coefficients are not equal:
w = pywt.Wavelet("coif5")
mlab.set_variable('Lo_D', w.dec_lo)
mlab_code = ("[lo_d, hi_d]=wfilters('coif5','d');")
res = mlab.run_code(mlab_code)
lo_d = np.asarray(mlab.get_variable('lo_d'))
np.sqrt(np.sum((lo_d - w.dec_lo)**2))
1.9951489141956095e-05

How to proceed?

**Comment by kwohlfahrt** [comment]
So far we've been using MATLAB as a reference. Where are the new coefficients from? Is there a good explanation for which of the two is more accurate?

If you are sure the new values are correct, then I think two steps:
- Increase the error allowed for MATLAB
- Create new fixtures (like for coif6+) for the remaining wavelets at a high accuracy.

**Comment by holgern** [comment]
The coefficients are calculated from 
 by Kazuo Hatano, Aichi Institute of Technology.
 * ftp://phase.etl.go.jp/pub/phase/wavelet/index.html
with fortran. I have a complete results table.

**Comment by kwohlfahrt** [comment]
I can't find any host for `phase.etl.go.jp`. The other two links provide values for Daubechies and Coif1-5, but not the remaining ones.

The two steps above are probably still the way forward. I'll be away for most of the weekend but will help with the rebase onto my PRs when I get back.

**Comment by holgern** [comment]
The table seems to be offline, but i have downloaded all coefficients.
You can find a publication of Kazuo Hatano with coefficients here:
http://repository.kulib.kyoto-u.ac.jp/dspace/bitstream/2433/60181/1/0944-26.pdf
It is in japan, but you can compare the numbers

**Comment by holgern** [comment]
The coefficients are also used in this book:
https://books.google.de/books?id=bJ8ySThsl1gC&pg=PA21&lpg=PA21&dq=Kazuo+Hatano+wavelet&source=bl&ots=c7KMo17ycz&sig=bO1udBx8YgIoVU5sRrCWL5vQOSA&hl=de&sa=X&ved=0ahUKEwi04sK99ajLAhWza5oKHTt8DkoQ6AEIJDAB#v=onepage&q=Kazuo%20Hatano%20wavelet&f=false

**Comment by holgern** [comment]
Ok, i merged my changes. Is everything ok now?

**Comment by kwohlfahrt** [comment]
I have opened a PR against your repository - it's mainly stylistic changes but also cuts out a few temporary allocations. Can you have a look at it and merge it if you agree with the changes? Otherwise I think this is good.

**Comment by holgern** [comment]
I agree with your changes and merged everything.

**Comment by kwohlfahrt** [comment]
I've just noticed that appveyor is failing at compile time, not at install time (which is the error we've been ignoring). I'm going to push a fix for it to master in a minute and try to see what is going on.

**Comment by holgern** [comment]
I uploaded a fix

**Comment by kwohlfahrt** [comment]
Great, this is +1 from me now. Lets give the others a day or two to review.

I'll push the appveyor fix to master in about 20 minutes (still testing on my branch). If you rebase after that we should have a nice green mark.

**Comment by aaren** [comment]
LGTM pending appveyor. Thanks @holgern! Feel free to attack any more of the wavelets in #165 - we can use that as a master issue (I'll update when I'm not on mobile).

**Comment by grlee77** [comment]
LGTM.  thanks

**Comment by kwohlfahrt** [comment]
Merging. Thanks @holgern :)

**Pull request merged**
