### PR TITLE
Add two new antisymmetric edge modes

### PR DESCRIPTION
**Pull request by grlee77**
This PR implements the two remaining edge modes supported by Matlab's `dwt` and as requested in #346.  

The matlab-based validation tests have been extended to also include these edge modes, so I don't think there is a concern about the correctness of the new implementation here, mainly just for style and to determine appropriate naming for the new modes.

I could use some feedback on what best to call these two new modes:

**We currently have:**
   Matlab's `sym` or 'symh' is equivalent to our 'symmetric'
   Matlab's 'symw' is equivalent to our 'reflect'
**For the two new modes in this PR:**
   Matlab's `asym` or `asymh` is equivalent to the mode `antisymmetric` implemented in this PR.
   Matlab's `asymw` is equivalent to the mode `antireflect` implemented in this PR.

I am not sure I like the name `antireflect`, but I am not sure what is a better alternative.  The `w` or `h` in the Matlab names indicates wether the (anti)symmetry is about a sample (called whole-sample symmetry, indicated by `w` in the Matlab names) or if the symmetry is about a point half-way between two samples (indicated by the `h` in the Matlab names.  Along those lines, an alternative naming scheme to use here would be:
`antisymmetric` -> `antisymmetric_half`
`antireflect` -> `antisymmetric_whole`
One other name I found in a single publication for what is called `antireflect` here was `doubly symmetric`, but it doesn't seem to be in common usage.

Visually, here is a comparison of all of these edge schemes including the two new ones from this PR (`antisymmetric` and `antireflect`).  The original signal is in red and the extended points are in black.  Vertical bars indicate points of extension or symmetry:
edge_modes

The antisymmetric implementation in `convolution.template.c` is a trivial modification of the existing code for `symmetric`.  It is just has some of the  `+=` changed to `-=` as needed.

The `antireflect` mode was a bit more complicated because the symmetry is not about amplitude 0, so it is not just a simple sign flip of the `reflect` case.  I will write a brief description of what is going on in a subsequent comment.  I came up with this implementation on my own based on working out what the loops should look like to produce the desired symmetry.

### CODE REVIEW

**Comment by grlee77** [comment]
To describe the implementation of `antireflect` in commit 71d36cd, refer to the following image where the original signal is indicated in red.  Vertical bars indicate points of anti-symmetry.
antireflect

The C code for extension immediately to the left of the `input` signal is given by:
```c
            // whole-sample anti-symmetric
            size_t k;
            TYPE le = input[0];    // current left edge value
            TYPE tmp = 0;
            while (j < F) {
                for(k = 1; k < N && j < F; ++j, ++k){
                    tmp = le - (input[k] - input[0]);
                    sum += filter[j]*tmp;
                }
                le = tmp;
                for(k = 1; k < N && j < F; ++j, ++k){
                    tmp = le + (input[N-1-k] - input[N-1]);
                    sum += filter[j]*tmp;
                }
                le = tmp;
            }
```
The first `for` loop covers the first segment between black vertical lines to the left of the red section.  The second `for` loop covers the second segment to the left of the red section.  The `while` loop then covers any additional segments to the left.  All of the symmetric and antisymmetric modes share this general structure.  Most often, in PyWavelets the signal is longer than the FIR filter for the wavelet so the second for loop and additional iterations of the while loop usually do not come into play. 

The value for the first black dot to the left of the red region should be the value at the edge point (`input[0]`) minus the difference between input[1] and input[0].
e.g.  `val = input[0] - (input[1] - input[0])`.  
This is what the first for loop is doing.

For subsequent reflections, the reflection is instead about the edge point from the prior reflection, so we need a variable, `le` (for left edge) here, to keep track of the current point we are reflecting about.  The difference terms such as `(input[k] - input[0])` stay the same for all reflections, just switching sign and iteration direction between the first and second for loops.  Put another way, within the `while` loop, the first `for` loop here covers any odd number of reflections while the second covers any even number of reflections.

There is a very similar while loops for extension from the right edge that operates on exactly the same principle.

**Comment by rgommers** [comment]
Would be nice to incorporate the code that generates the image that's now included as a png.

**Comment by grlee77** [comment]
Okay. I modified the final commit to replace the png file with a script that will generate it on the fly during the documentation build.

**Comment by rgommers** [comment]
LGTM, thanks @grlee77!

And thanks for the detailed explanation of the for/while loops above. I suspect that that'll come in handy in the future. That code isn't exactly easy to understand, even though there are some terse comments in the code pointing in a similar direction to your comment above.

**Pull request merged**
