### PR TITLE
Add pyqtgraph demo for plotting wavelets

### PR DESCRIPTION
**Pull request by michelp**
This is similar to plot_wavelets.py demo except it uses pyqtgraph, where each wavelet is in its own plot and can be zoomed.

Attached is a screenshot, each wavelet family is on its own tab, this shows bior:

wavelets

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @michelp. This looks good to me. 

Don't have PyQt4 installed right now (and that's a pain), so will wait to see if someone else has it installed to try this out and merge.

**Comment by grlee77** [comment]
I tried it out and it works nicely.  The only problem is see is that for the Debauchies wavelets there are 76 subplots (phi, psi for all 38 `db` wavelets in release 0.5.0).  Maybe split into two or three separate tabs (e.g. db1-19, db20-38) for better visibility?

**Comment by michelp** [comment]
I was hesitant to split a family across tabs, so I thought a good compromise was to add a scroll bar and let family spill downward.  I've attached a screenshot of the bior tab scrolled.
demoscrolled

**Comment by grlee77** [comment]
Thanks @michelp , that is a better solution and makes everything much more visible, especially on smaller displays!  I will need to take a closer look at `pyqtgraph` sometime.

I am happy to merge this as is, but if you are interested, the recent release 0.10 of `pyqtgraph` should make it possible for the demo to support Qt5 (the default for anaconda) and PySide as well.  In the `pyqtgraph` examples I see things like:
```python
from pyqtgraph.Qt import QtGui, USE_PYSIDE, USE_PYQT5
```

**Comment by grlee77** [comment]
I just tested locally with PyQt5 from anaconda and the only change needed to get it to work is to replace
```from PyQt4 import QtGui```
with
```from pyqtgraph.Qt import QtGui```

Can you please make that small change here as well?  It should still be compatible with the older pyqtgraph 0.9.0 too.

**Comment by michelp** [comment]
Thanks @grlee77 that fix works here for me as well and I've pushed it.

**Comment by grlee77** [comment]
If you are familiar with rebasing, can you squash the first 4 commits into 1?  Other than that, I think this is good to go.

**Comment by michelp** [comment]
All squashed up, thanks @grlee77 !

**Comment by grlee77** [comment]
Thanks @michelp

**Pull request merged**
