### PR TITLE
Rename master branch to main

### PR DESCRIPTION
**Pull request by jarrodmillman**
Not a big deal, if you don't want to make the change.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks Jarrod. This seems like a good idea to me. The slower-moving projects that are still using `master` instead of `main` are tripping me up, muscle memory has changed by now:) And it's a good thing to do anyway.

There may be a few merge conflicts in other PRs if we do this, but nothing too serious I believe. @grlee77 are you okay with this change?

**Comment by rgommers** [comment]
I'd like to merge this one before the next release (v1.6.0), but only after the other currently active PRs have been merged.

**Comment by agriyakhetarpal** [comment]
Hi @jarrodmillman and @rgommers, we should be able to merge this now and get the release going.

**Comment by jarrodmillman** [comment]
I will rebase and respond later today.

**Review by agriyakhetarpal — APPROVED** [review]
Thank you, @jarrodmillman! From my end I can find no other references, will leave it to Ralf if there is anything I missed

**Review by rgommers — APPROVED** [review]
Okay, let's give this a go now - thanks Jarrod! And thanks for the review Agriya!

**Comment by rgommers** [comment]
Okay, `main` is up - will check the CI jobs, but should be all good now it looks like.

**Comment by rgommers** [comment]
For completeness: all nightlies built and uploaded fine from `main`, all set here.

**Pull request merged**
