### PR TITLE
backporting bug fixes from master to 0.5.2

### PR DESCRIPTION
**Pull request by grlee77**
incorporates: #273, #276, #289, #291, #292, #294, #295

@rgommers.  I wasn't sure of the best way to get the specific changes from the PRs above from master to 0.5.x.  Here I checked out a branch based on 0.5.x and did cherry-picks of the commits for each PR above.  There were only a few minor conflicts to resolve.

Should there instead be a separate PR for each of the issues above instead of putting them all together like this?

I can add release notes for 0.5.2 in a separate PR in the next day or so.

### CODE REVIEW

**Comment by rgommers** [comment]
I like putting them all together. Cuts down on the noise; no code review is needed after all, just checking that the commits are the right ones.

> Here I checked out a branch based on 0.5.x and did cherry-picks of the commits for each PR above.

That's how I usually do it.

**Comment by rgommers** [comment]
TravisCI is already unhappy.

**Comment by grlee77** [comment]
Had to specify `matplotlib<2` for Python 2.6 case on Travis.  I did this as this branch still supports 2.6, but we have only previously tested these PRs on 2.7+

**Comment by rgommers** [comment]
All green, so in it goes.

**Pull request merged**
