### PR TITLE
Adding travis CI support for ARM64

### PR DESCRIPTION
**Pull request by ossdev07**
Travis-CI has added support for ARM64. Added ARM64 job in Travis-CI.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @ossdev07, I think this is a good idea. I would suggest to only use a single ARM64 job though, because testing every combination of architecture and Python version is not needed and may lead to using too many CI resources. I suggest just Python 3.6 or 3.7 for now. 3.5 we're dropping anyway before the next release.

Despite the green CI status, the ARM64 jobs have a test error:
```
________________________ ERROR collecting test session _________________________

../../../../virtualenv/python3.6.9/lib/python3.6/site-packages/_pytest/config/__init__.py:451: in _importconftest

    return self._conftestpath2mod[key]

E   KeyError: PosixPath('/home/travis/build/PyWavelets/pywt/pywt/conftest.py')
```
could you look into that?

**Comment by grlee77** [comment]
Yes, thanks for adding this!

It looks like there are also some doctest errors, although they look like just a minor precision/formatting issue and not real bugs. I suppose we could configure the Travis ARM runs to just skip running the doctests.

```
File "/home/travis/build/PyWavelets/pywt/doc/source/regression/wp2d.rst", line 108, in wp2d.rst

Failed example:

    print(wp['h'].data)

Expected:

    [[ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]]

Got:

    [[  0.00000000e+00  -7.85046229e-17  -7.85046229e-17   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17  -7.85046229e-17   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17  -7.85046229e-17   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17  -7.85046229e-17   2.35513869e-16]]
```

**Comment by ossdev07** [comment]
Ping @rgommers  we have incorporated the changes according to your suggestion kindly have a look on this commit

**Comment by rgommers** [comment]
@ossdev07 there was no change to the broken behavior. Copying the output from one of the test suite runs here:

<details>

```
==================================== ERRORS ====================================

________________________ ERROR collecting test session _________________________

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/config/__init__.py:451: in _importconftest

    return self._conftestpath2mod[key]

E   KeyError: PosixPath('/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/pywt/conftest.py')

During handling of the above exception, another exception occurred:

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/config/__init__.py:457: in _importconftest

    mod = conftestpath.pyimport()

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport

    __import__(modname)

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/pywt/__init__.py:14: in <module>

    from distutils.version import LooseVersion

../../../../virtualenv/python3.7.5/lib/python3.7/distutils/__init__.py:4: in <module>

    import imp

../../../../virtualenv/python3.7.5/lib/python3.7/imp.py:33: in <module>

    DeprecationWarning, stacklevel=2)

E   DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

During handling of the above exception, another exception occurred:

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/runner.py:229: in from_call

    result = func()

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/runner.py:256: in <lambda>

    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/main.py:487: in collect

    yield from self._collect(arg)

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/main.py:514: in _collect

    col = self._collectfile(pkginit, handle_dupes=False)

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/main.py:583: in _collectfile

    ihook = self.gethookproxy(path)

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/main.py:426: in gethookproxy

    my_conftestmodules = pm._getconftestmodules(fspath)

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/config/__init__.py:429: in _getconftestmodules

    mod = self._importconftest(conftestpath)

../../../../virtualenv/python3.7.5/lib/python3.7/site-packages/_pytest/config/__init__.py:465: in _importconftest

    raise ConftestImportFailure(conftestpath, sys.exc_info())

E   _pytest.config.ConftestImportFailure: (local('/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/pywt/conftest.py'), (<class 'DeprecationWarning'>, DeprecationWarning("the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses"), <traceback object at 0xffff7fb34730>))

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!

=============================== 1 error in 0.58s ===============================

......................................FF.......

======================================================================

FAIL: /home/travis/build/PyWavelets/pywt/doc/source/regression/wp2d.rst

Doctest: wp2d.rst

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/opt/python/3.7.5/lib/python3.7/doctest.py", line 2196, in runTest

    raise self.failureException(self.format_failure(new.getvalue()))

AssertionError: Failed doctest test for wp2d.rst

  File "/home/travis/build/PyWavelets/pywt/doc/source/regression/wp2d.rst", line 0

----------------------------------------------------------------------

File "/home/travis/build/PyWavelets/pywt/doc/source/regression/wp2d.rst", line 108, in wp2d.rst

Failed example:

    print(wp['h'].data)

Expected:

    [[ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]]

Got:

    [[  0.00000000e+00  -7.85046229e-17  -7.85046229e-17   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17  -7.85046229e-17   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17  -7.85046229e-17   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17  -7.85046229e-17   2.35513869e-16]]

----------------------------------------------------------------------

File "/home/travis/build/PyWavelets/pywt/doc/source/regression/wp2d.rst", line 118, in wp2d.rst

Failed example:

    print(wp['d'].data)

Expected:

    [[ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]]

Got:

    [[  0.00000000e+00  -7.85046229e-17   2.35513869e-16   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17   2.35513869e-16   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17   2.35513869e-16   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17   2.35513869e-16   2.35513869e-16]]

----------------------------------------------------------------------

File "/home/travis/build/PyWavelets/pywt/doc/source/regression/wp2d.rst", line 425, in wp2d.rst

Failed example:

    print(wp.d)

Expected:

    d: [[ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]

     [ 0.  0.  0.  0.]]

Got:

    d: [[  0.00000000e+00  -7.85046229e-17   2.35513869e-16   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17   2.35513869e-16   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17   2.35513869e-16   2.35513869e-16]

     [  0.00000000e+00  -7.85046229e-17   2.35513869e-16   2.35513869e-16]]

======================================================================

FAIL: /home/travis/build/PyWavelets/pywt/doc/source/regression/multilevel.rst

Doctest: multilevel.rst

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/opt/python/3.7.5/lib/python3.7/doctest.py", line 2196, in runTest

    raise self.failureException(self.format_failure(new.getvalue()))

AssertionError: Failed doctest test for multilevel.rst

  File "/home/travis/build/PyWavelets/pywt/doc/source/regression/multilevel.rst", line 0

----------------------------------------------------------------------

File "/home/travis/build/PyWavelets/pywt/doc/source/regression/multilevel.rst", line 51, in multilevel.rst

Failed example:

    print(cD2)

Expected:

    [ 3.   3.5  0.  -4.5 -3.   0.5  0.   0.5]

Got:

    [  3.00000000e+00   3.50000000e+00  -1.70656864e-16  -4.50000000e+00

      -3.00000000e+00   5.00000000e-01  -3.61606800e-16   5.00000000e-01]

----------------------------------------------------------------------

File "/home/travis/build/PyWavelets/pywt/doc/source/regression/multilevel.rst", line 57, in multilevel.rst

Failed example:

    print(cD2)

Expected:

    [ 3.   3.5  0.  -4.5 -3.   0.5  0.   0.5]

Got:

    [  3.00000000e+00   3.50000000e+00  -1.70656864e-16  -4.50000000e+00

      -3.00000000e+00   5.00000000e-01  -3.61606800e-16   5.00000000e-01]

----------------------------------------------------------------------
```

</details>

So there's two issues:
- CI is green while there are clearly test errors so exit code is wrong (I suggest fixing this one first)
- Test suite doesn't pass

**Comment by ossdev07** [comment]
@rgommers , @grlee77 ,
We are getting below result while running the doctest in arm64: 

File | Parameter | X86 | ARM64
-- | -- | -- | --
doc/source/regression/wp2d.rst     Command: "print(wp['h'].data)" and   "print(wp['d'].data)" | Result | [[ 0. 0. 0. 0.]     [ 0. 0. 0. 0.]     [ 0. 0. 0. 0.]     [ 0. 0. 0. 0.]] | [[ 0.00000000e+00 -7.85046229e-17   2.35513869e-16 2.35513869e-16]     [ 0.00000000e+00 -7.85046229e-17 2.35513869e-16 2.35513869e-16]     [ 0.00000000e+00 -7.85046229e-17 2.35513869e-16 2.35513869e-16]     [ 0.00000000e+00 -7.85046229e-17 2.35513869e-16 2.35513869e-16]]
doc/source/regression/multilevel.rst     Command: "print(cD2)" | Result | [ 3. 3.5 0. -4.5 -3. 0.5 0. 0.5] | [ 3.00000000e+00 3.50000000e+00 -1.70656864e-16   -4.50000000e+00     -3.00000000e+00 5.00000000e-01 -3.61606800e-16 5.00000000e-01]

The above command gives different results on X86 and ARM64.
Can you please share your opinion regarding above behavior. 
Also please confirm, should be configure the Travis ARM runs to just skip running the doctests as per https://github.com/PyWavelets/pywt/pull/539#issuecomment-570633589?

**Comment by grlee77** [comment]
> Also please confirm, should be configure the Travis ARM runs to just skip running the doctests as per #539 (comment)?

I think so. The tests run by pytest will verify the expected behavior of the transforms. The doctests are older.  I think their main benefit is just checking that the examples in the documentation work and don't become out of sync as the library is updated.

**Comment by ossdev07** [comment]
@rgommers , @grlee77 ,
Configured Travis to skip running the doctests for ARM64. Kindly have a look on this commit.

**Comment by grlee77** [comment]
Thanks. It looks good to me. I will merge in a day or two if there are no objections.

**Comment by grlee77** [comment]
Thanks @ossdev07, I will go ahead and merge this now. 

@rgommers, I see that you had suggested performing only one ARM64 build to conserve CI resources. If you still want to do that we can remove one of the cases in a follow-up PR.

**Comment by grlee77** [comment]
@ossdev07: If you want your full name rather than your GitHub username to show up in the release notes for a future release, please provide it here.

**Pull request merged**
