### PR TITLE
WIP: test against Python 3.8

### PR DESCRIPTION
**Pull request by grlee77**
This PR is an attempt to test against Python 3.8.

### CODE REVIEW

**Comment by grlee77** [comment]
Python 3.8 is passing!

The `DISTUTILS_USE_SDK` case is now failing because I removed Python 3.4 where it was being used and moved this case to 3.5. I think the `util/appveyor/build.cmd` would have to be updated to use a different version of MSVC/SDK than 3.4 did.

**Comment by grlee77** [comment]
I think we should just remove DISTUTILS_USE_SDK and all will be well

**Comment by grlee77** [comment]
Actually the tests for 3.8 were not run on Travis due to some pytest-related import error causing 0 tests to be found:

https://travis-ci.org/PyWavelets/pywt/jobs/599345508#L917-L954

**Comment by grlee77** [comment]
I don't understand the import error on Travis, particularly the following section
```
../../../../virtualenv/python3.8.0/lib/python3.8/distutils/__init__.py:4: in <module>

    import imp
```
In my local copy of Python 3.8 there is no `import imp` at this location.

The test suite ran normally on Python 3.8 when I tried it locally on a 64-bit linux machine.

**Comment by grlee77** [comment]
Marking this as WIP for now. I don't think it is useful to merge as is since the tests on 3.8 are not currently being run.

They did get run over at MacPython/pywavelets-wheels#9 and are passing there, so I think we can work on this again after the 1.1 release.

**Comment by rgommers** [comment]
Ah I missed this one - should we merged as is?

**Comment by grlee77** [comment]
Let me take a quick look again first. I think #540 might have fixed one of the issues here, but I think we may not need  8bb8661 and I see that the Appveyor case is still commented out here for some reason.

**Comment by grlee77** [comment]
Okay, I think this looks good now. Probably want to squash the commits on merge to get rid of some of the noise (or I can do it manually if you prefer)

**Pull request merged**
