### PR TITLE
Move (most) Travis-CI jobs to GitHub Actions

### PR DESCRIPTION
**Pull request by grlee77**
This moves most of the CI that was on Travis to GitHub actions. There is one arm64 case remaining on Travis.

### CODE REVIEW

**Comment by grlee77** [comment]
Not sure why the GitHub Actions workflow isn't getting triggered here. It did in https://github.com/grlee77/pywt/pull/10 where I was testing.

(It looks like Actions are enabled in the repository settings)

**Comment by rgommers** [comment]
It won't trigger on PRs from forks if the `on: ...` block isn't in master yet. That's a security feature, otherwise random people can submit PRs on repos to get free CPU hours. You can just merge it and iterate.

**Comment by grlee77** [comment]
> It won't trigger on PRs from forks if the on: ... block isn't in master yet. That's a security feature, otherwise random people can submit PRs on repos to get free CPU hours. You can just merge it and iterate.

Okay, thanks. let's make sure the one currently running on my fork succeeds and then we can merge here.

**Comment by grlee77** [comment]
All is green after merge: https://github.com/PyWavelets/pywt/actions/runs/907402902

**Comment by rgommers** [comment]
Thanks for modernizing our CI!

**Pull request merged**
